<%@ page language="java" autoFlush="true" contentType="text/html; charset=UTF-8"%><%

   String scheme = request.getScheme();
   String serverName = request.getServerName();
   int serverPort = request.getServerPort();

   String serverAddress = scheme + "://" + serverName + ":" + serverPort;

   response.setContentType("text/plain");
%>#
# robots.txt generated by Nesstar Server
# Read more about the robots exclusion standard here http://en.wikipedia.org/wiki/Robots.txt 
#

User-agent: *
Allow: /webview/index
Disallow: /webview/static
Disallow: /webview/velocity
Disallow: /webview/velocityembedded
Disallow: /webview/skins
Disallow: /webview/main.jsp
Disallow: /webview/rightside.jsp
Disallow: /nesstar
Disallow: /browser
Disallow: /admin
Disallow: /console
Disallow: /obj
Sitemap: <%=serverAddress%>/webview/index/sitemap.xml